### ISSUE TITLE
Archive this repo

### ISSUE THREAD

**Issue by ann0see** [ann0see/gandalfnewapp#2]
@mehulrao @EthanRDoesMC

Since gandalf isn't actively developed anymore, I think we should archive this repo. Furthermore, we should add a license to this so that everybody can use this app if he wants.

MIT license?

**Comment by EthanRDoesMC** [comment]
Indeed, and I think I'll do the same for the main Gandalf repo. Its time has come and passed, which is the best possible outcome, really. (IIRC, doubleh3lix, h3lix, and Meridian all have far greater compatibility with tweaks, so there's no reason to use Yalu -- and by extension, Gandalf -- anymore.)


MIT license sounds good -- we had some interesting build scripts and even an uncommon workaround for dpkg, so someone might find some use out of it. 


Fun while it lasted, though! :)

**Comment by ann0see** [comment]
I think I‘ll need to clean this repo up first.

**Comment by ann0see** [comment]
Although not everything is "clean", I think I can now live with this state being archived.

**Comment by ann0see** [comment]
Ok. Archiving this now ;-).

**Comment by ann0see** [comment]
BTW. Thanks for all your work and the great time we had!
